# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='denuncia',
            field=models.TextField(blank=True, null=True, verbose_name='Denûncia'),
        ),
        migrations.AddField(
            model_name='local',
            name='imagem',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='local',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='longitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
