# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0002_auto_20170505_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
    ]
