# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0003_auto_20170510_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='codusuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mapa_app.Usuario'),
            preserve_default=False,
        ),
    ]
