# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0005_auto_20170510_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='datamensagem',
            field=models.DateField(),
        ),
    ]
