# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0007_mensagem_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='dt_atualiza',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='local',
            name='dt_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='local',
            name='codusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='resposta',
            field=models.CharField(choices=[('0', 'Não atendido'), ('1', 'Atendido')], default=0, max_length=1, verbose_name='Resposta'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
