# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0009_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='datamensagem',
        ),
        migrations.AddField(
            model_name='teste',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email: '),
        ),
        migrations.AddField(
            model_name='teste',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha: '),
        ),
        migrations.AlterField(
            model_name='teste',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do voluntário: '),
        ),
    ]
