# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0010_auto_20170729_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100, verbose_name='Nome')),
                ('senha', models.TextField(max_length=100, verbose_name='Senha')),
                ('email', models.TextField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
            },
        ),
        migrations.DeleteModel(
            name='teste',
        ),
    ]
