# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0011_auto_20170729_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.RemoveField(
            model_name='local',
            name='codusuario',
        ),
        migrations.RemoveField(
            model_name='local',
            name='denuncia',
        ),
        migrations.RemoveField(
            model_name='local',
            name='dt_atualiza',
        ),
        migrations.RemoveField(
            model_name='local',
            name='dt_cadastro',
        ),
        migrations.RemoveField(
            model_name='local',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=100, verbose_name='Senha'),
        ),
    ]
