# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0012_auto_20170729_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='altura',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
