# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0013_local_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abrigo')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cep')),
                ('espaco', models.CharField(blank=True, max_length=15, null=True, verbose_name='Espaço disponivel')),
            ],
            options={
                'verbose_name': 'Abrigo',
                'verbose_name_plural': 'Abrigos',
            },
        ),
    ]
