# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0015_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrigado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('necessidade', models.CharField(choices=[('0', 'Locomoção'), ('1', 'Abrigo'), ('2', 'Mantimentos'), ('3', 'Brinquedos'), ('4', 'Vestimentas/Cobertores')], default=0, max_length=1, verbose_name='Necessidade')),
                ('quantidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Abrigado',
                'verbose_name_plural': 'Abrigados',
            },
        ),
    ]
