# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0016_abrigado'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='cep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='cpf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de telefone'),
        ),
    ]
