# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0018_auto_20170730_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrirelaciona',
            name='codusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunta', to='mapa_app.Voluntario'),
        ),
    ]
