# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0019_auto_20170730_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abrirelaciona',
            name='codabrigo',
        ),
    ]
