# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0020_remove_abrirelaciona_codabrigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrirelaciona',
            name='codabrigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapa_app.Abrigo'),
            preserve_default=False,
        ),
    ]
