# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_app', '0021_abrirelaciona_codabrigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='altura',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
